/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.StringNullException;
import control.CardControl;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Card;

/**
 *
 * @author aluno
 */
public class FrmCard extends javax.swing.JFrame {

    private CardControl cards;
    private DefaultTableModel tbl;
    /**
     * Creates new form FrmCard
     */
    public FrmCard() {
        tbl = new DefaultTableModel();
        cards = new CardControl();
        initComponents();
        tbl.addColumn("Numero");
        tbl.addColumn("Nome");
        tbl.addColumn("Clube");
        tbl.addColumn("Nacionalidade");
        tbl.addColumn("Liga");
        tbl.addColumn("Overall");
        tbl.setRowCount(0);
        tblClients.setModel(tbl); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadastroLiga = new javax.swing.JLabel();
        lblCadastroOverall = new javax.swing.JLabel();
        btnCadastro = new javax.swing.JButton();
        lblCadastro = new javax.swing.JLabel();
        lblCadastroNome = new javax.swing.JLabel();
        lblCadastroNumero = new javax.swing.JLabel();
        lblCadastroNacionalidade = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClients = new javax.swing.JTable();
        lblBuscar = new javax.swing.JLabel();
        txtBuscarNome = new javax.swing.JTextField();
        lblBuscarNome = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        lblExcluir = new javax.swing.JLabel();
        txtExcluirNome = new javax.swing.JTextField();
        lblExcluirNome = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        lblCadastroClube = new javax.swing.JLabel();
        txtCadastroNumero = new javax.swing.JTextField();
        txtCadastroNome = new javax.swing.JTextField();
        txtCadastroClube = new javax.swing.JTextField();
        txtCadastroNacionalidade = new javax.swing.JTextField();
        txtCadastroLiga = new javax.swing.JTextField();
        txtCadastroOverall = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCadastroLiga.setText("Liga:");

        lblCadastroOverall.setText("Overall:");

        btnCadastro.setText("Cadastrar");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        lblCadastro.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCadastro.setText("Cadastro Card");

        lblCadastroNome.setText("Nome:");

        lblCadastroNumero.setText("Numero:");

        lblCadastroNacionalidade.setText("Nacionalidade:");

        tblClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Nome", "Clube", "Nacionalidade", "Liga", "Overall"
            }
        ));
        jScrollPane1.setViewportView(tblClients);

        lblBuscar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblBuscar.setText("Buscar Card");

        txtBuscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarNomeActionPerformed(evt);
            }
        });

        lblBuscarNome.setText("Nome:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblExcluir.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblExcluir.setText("Excluir Card");

        txtExcluirNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExcluirNomeActionPerformed(evt);
            }
        });

        lblExcluirNome.setText("Nome:");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblCadastroClube.setText("Clube:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblExcluirNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtExcluirNome))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCadastroOverall)
                            .addComponent(lblCadastroLiga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCadastroLiga)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtCadastroOverall))))
                    .addComponent(btnCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCadastroNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadastroNome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCadastroNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadastroNumero))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCadastroNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCadastroNacionalidade))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCadastroClube)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadastroClube))
                            .addComponent(lblExcluir)
                            .addComponent(lblCadastro)
                            .addComponent(lblBuscar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBuscarNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCadastro)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCadastroNumero)
                            .addComponent(txtCadastroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCadastroNome)
                            .addComponent(txtCadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCadastroClube)
                            .addComponent(txtCadastroClube, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCadastroNacionalidade)
                            .addComponent(txtCadastroNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCadastroLiga)
                            .addComponent(txtCadastroLiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCadastroOverall)
                            .addComponent(txtCadastroOverall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBuscarNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtExcluirNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblExcluirNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExcluirNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExcluirNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExcluirNomeActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        try{
            String nome = txtCadastroNome.getText();
            String nacionalidade = txtCadastroNacionalidade.getText();
            String liga = txtCadastroLiga.getText();
            String clube = txtCadastroClube.getText();
            JOptionPane.showMessageDialog(null, clube + " . " + txtCadastroNome.getText() + " " + nacionalidade + " " + liga);
            if("".equals(nome) || "".equals(nacionalidade) || "".equals(liga) || "".equals(clube)){
                throw new StringNullException();
            }

            int numero = Integer.parseInt(txtCadastroNumero.getText());
            int overall = Integer.parseInt(txtCadastroOverall.getText());
            if(numero  <= 0 || overall <=0 ){
                throw new NumberFormatException();
            }
            cards.incluir(numero, nome, clube, nacionalidade, liga, overall);
            atualizaTabela();
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Não foi possível incluir o Card");
            System.out.println("Erro ao incluir Card "  + e.toString());
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Não insira texto em campos que pedem números ou overall!");
        }
        catch(StringNullException e){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de cadastrar!");
        }
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try{
            String nome = txtBuscarNome.getText();
            if("".equals(nome)){
                throw new StringNullException();
            }
            ArrayList<Card> lista = cards.BuscarPorNome(nome);
            for(Card c: lista){
                tbl.setRowCount(0);
                tbl.addRow(new Object[]{c.getNumber(),c.getName(),c.getClub(),c.getNationality(),c.getLeague(),c.getOverall()});
            }
            tblClients.setModel(tbl);
        }
        catch(StringNullException e){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de Buscar!");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarNomeActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try{
            String nome = txtExcluirNome.getText();
            if("".equals(nome)){
                throw new StringNullException();
            }
            cards.ExcluirCard(nome);
            atualizaTabela();
        }
        catch(StringNullException e){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de Excluir!");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Não foi possível achar nenhum card com tal nome!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCard().setVisible(true);
            }
        });
    }

    public void atualizaTabela(){
        tbl.setRowCount(0);
        try{
            ArrayList<Card> lista = cards.BuscarTodos();
            for(Card c: lista){
                tbl.addRow(new Object[]{c.getNumber(),c.getName(),c.getClub(),c.getNationality(),c.getLeague(),c.getOverall()});
            }
            tblClients.setModel(tbl);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Não foi possível achar nenhum card com tal nome!");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblBuscarNome;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblCadastroClube;
    private javax.swing.JLabel lblCadastroLiga;
    private javax.swing.JLabel lblCadastroNacionalidade;
    private javax.swing.JLabel lblCadastroNome;
    private javax.swing.JLabel lblCadastroNumero;
    private javax.swing.JLabel lblCadastroOverall;
    private javax.swing.JLabel lblExcluir;
    private javax.swing.JLabel lblExcluirNome;
    private javax.swing.JTable tblClients;
    private javax.swing.JTextField txtBuscarNome;
    private javax.swing.JTextField txtCadastroClube;
    private javax.swing.JTextField txtCadastroLiga;
    private javax.swing.JTextField txtCadastroNacionalidade;
    private javax.swing.JTextField txtCadastroNome;
    private javax.swing.JTextField txtCadastroNumero;
    private javax.swing.JTextField txtCadastroOverall;
    private javax.swing.JTextField txtExcluirNome;
    // End of variables declaration//GEN-END:variables
}
